# Site settings
title: Sebasti치n Fern치ndez
description: Embedded Systems Engineer
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sef.ar" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sebasti치n Fern치ndez
user_description: I'm a Embedded Systems Engineer from Argentina, always searching for the next challenge. More than 5 years experience in analysis, design, development, testing, and implementation of various embedded systems.
user_title: Embedded Systems Engineer
email: info@sef.ar
# twitter_username: 
# instagram_username: 
# facebook_username: 
linkedin_username: sefernandez 
github_username:  iojan
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
